GRANT ALL PRIVILEGES ON DATABASE tunit TO tunitefm;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

\c tunit

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tunitefm;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tunitefm;